apiVersion: v1
kind: ConfigMap
metadata:
  name: v7-games-backend-config
  labels:
    app: v7-games-backend
data:
  # Application environment for logging and operational behavior.
  APP_ENV: "production"
  # Default log level for the backend service.
  LOG_LEVEL: "INFO"
  # Placeholder for any future non-sensitive application-specific settings,
  # such as feature flags or external service URLs that are not secrets.
  # For example:
  # API_BASE_URL: "https://api.v7games.com"