apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ancestral-dough-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard # Uncomment and set if you have a specific storage class (e.g., 'gp2' on AWS, 'standard' on GKE)